name: "Build"
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build:
    name: Build and push brandi docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: cachix/install-nix-action@v10
    - uses: cachix/cachix-action@v6
      with:
        name: brandi
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

    - name: Login to DockerHub Registry
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - run: nix-build ./docker.nix

    - run: docker load -i ./result
    - run: docker push channikhabra/brandi:latest
